mm-rmap-use-huge_ptep_get-in-try_to_migrate_one-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'Commit a98a2f0c8ce1 ("mm/rmap: split migration into its own function")'
#18: 
Commit a98a2f0c8ce1 copied the bug from try_to_unmap_one into

WARNING: braces {} are not necessary for any arm of this statement
#74: FILE: mm/rmap.c:2504:
+		if (folio_test_hugetlb(folio)) {
[...]
+		} else {
[...]

total: 1 errors, 1 warnings, 31 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-rmap-use-huge_ptep_get-in-try_to_migrate_one.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Dev Jain <dev.jain@arm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>